### ISSUE TITLE
Send files from Telegram to Discord

### ISSUE THREAD

**Issue by CanineHybrid** [Suppen/TediCross#12]
With the recent update #4, attachments/files uploaded to Discord will be posted to Telegram as a downloadable link (yey!), but any files from Telegram will not appear as a message from the bot on Discord at all.

The media type that is currently shared from Telegram to Discord properly are image files, but _only_ if they are sent as "compressed", as well as certain links that support media previews.

Would be a wonderful feature for all media attachments uploaded from Telegram to be cross posted in Discord too, now that it works from one side.

**Comment by trgwii** [comment]
Discord apparently supports [attachments](https://discordapp.com/developers/docs/resources/channel#attachment-object)
I'm not sure if directly exposing the file URL that Telegram provides the bots to Discord may be a security concern, if not, that's a possibility

**Comment by Suppen** [comment]
I don't think this is a big problem to do. Will see what I can do this weekend

**Comment by Suppen** [comment]
@trgwii The images count as attachments. The URL appears to be https://cdn.discordapp.com/attachments/<server or channel ID>/<message ID>/<filename>
I don't think there's a security risk to send that to Telegram. As far as I know, you can't join a Discord server just by knowing its ID. You need an invite link to do that.

The link is also sent to anyone in the Discord chat. If you click "Open original", it opens the URL in the browser

**Comment by Suppen** [comment]
Partially solved now. The Telegram API is a bit difficult here. The types photo, audio, video, sticker, voice and document need to be handled separately.

TediCross now handles photo, audio and documents. The other types will not yet go through.

Audio files will not necessarily get their correct names, as it is actually not possible to get the file name for an audio file with the bot API. Instead, TediCross constructs a file name from the title of the audio file, which can be either the original file name or whatever tags are in the audio file.

**Comment by Suppen** [comment]
Video and stickers are now handled as well

**Comment by Suppen** [comment]
I consider this done. If there is any file type which is not sent correctly, please let me know
