### ISSUE TITLE
Black/whitelisting specific user and bot messages

### ISSUE THREAD

**Issue by CanineHybrid** [Suppen/TediCross#13]
Currently, only messages from human users will be cross-posted. Naturally bots were not included because the TediCross bots would constantly mirror each other and create an infinite loop of each other's messages between Telegram and Discord.

However I do have a few other bots in my chats alongside my TediCross bots that I would love to be able to cross-post their messages too. Think there's any way you could add the ability to black/whitelist certain bots and even specific users?

**Comment by Suppen** [comment]
This is a limitation of the Telegram Bot API. Telegram bots cannot under any circumstances get each other's messages (at least that was the case last time I checked).

Discord bots, however, are able to get each other's messages. They even get their own messages, so I have to specifically filter those out.

With the exception of the Discord bot filtering itself, there is no filtering of whose messages are relayed.

**Comment by Suppen** [comment]
Quoting the [Telegram Bot FAQ](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots)

**Why doesn't my bot see messages from other bots?**
Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.
