### ISSUE TITLE
Error: Incorrect login details were provided

### ISSUE THREAD

**Issue by YoYo-Pete** [Suppen/TediCross#14]
Hiya...

First thanks for publishing your work.. it's much appreciated.

I'm trying to setup your bot, but am having an issue on the discord side.  The bot connects successfully to Telegram but does not show as 'online' in discord.

My error is:

    Telegram: SOC_Relay_Bot (363152045)
    (node:25763) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Incorrect login details were provided.
    (node:25763) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am thinking it's a config error with settings.json (mybe)

Bot Token = is good on my end, and bot is in user mode.

ServerID = Also called Guild ID, I find this in my widget.  I think this is good on my end.

**ChannelID - I have no idea what to use here or where to find this.**

usersfile - is this something I need to create or worry about?  My understanding is that this is the file the bot interacts with and creates if it doesnt exist?

**Comment by YoYo-Pete** [comment]
I'm using the same ID for Channel ID and Server ID (which I believe is correct)

**Comment by Suppen** [comment]
Solved through a Telegram chat. The issue was that YoYo-Pete used the "Client Secret" instead of the "Token". For future reference: The token is under "App bot user", not under "App details"

**Comment by Suppen** [comment]
I updated step 7 in the readme to point this out

**Comment by denyx04** [comment]
> Solved through a Telegram chat. The issue was that YoYo-Pete used the "Client Secret" instead of the "Token". For future reference: The token is under "App bot user", not under "App details"

Thanks, you actually solved my problem.
