### ISSUE TITLE
Markdown parser too greedy

### ISSUE THREAD

**Issue by Suppen** [Suppen/TediCross#19]
Posting an URL like for example `http://example.com/cake_cheese_sauce` in Discord will make it arrive in Telegram with "cheese" in italic, and no traces of the underscores

**Comment by Suppen** [comment]
I can't find documentation for the markdown parser used in Discord anywhere, so anything I do will be guesswork. If anyone can track down any documentation, or find the actual implementation in the discord client, please tell me

**Comment by Suppen** [comment]
Maybe something here? https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

**Comment by alphachung** [comment]
In Discord’s [acknowledgements page](https://discordapp.com/acknowledgements), they seem to be using @Khan/simple-markdown

**Comment by Suppen** [comment]
Thanks for the info, @alphachung. I tried rewriting the parser using simple-markdown. It appears to almost correctly parse Discord-flavored markdown, struggling with shrug (`¯\_(ツ)_/¯` becoming `¯_(ツ)_/¯`) and custom HTML in the text not being escaped (`<b>` staying that way instead of becoming `&lt;b&gt;`, but this is easy enough to fix)

Telegram, however, will not always accept the HTML output. Specifically it appears to struggle with nested tags. `<strong><em>something</em></strong>` is rejected by Telegram.

I also did a test to see what happens when I pass the unparsed markdown from Discord to Telegram and the other way. I sent this text:

    *italics*
    **bold**
    ***bold italics***
    __underline__
    __*underline italics*__
    __**underline bold**__
    __***underline bold italics***__
    `code line`
    ```
    code block
    ```
    <strong>Custom HTML</strong>

both ways, using the Telegram bot @bold to be able to give markdown to Telegram. The result:

![bilde](https://user-images.githubusercontent.com/12338293/28500099-4b2de5e4-6fc3-11e7-9750-60a9664fe19f.png)

Telegram and Discord apparently uses very different markdown.

Ideally, I could just keep it this way, not doing any parsing and sending anything as raw markdown from Discord to Telegram. This will, however, result in some messages being rejected by Telegram for having invalid markdown. Trying to give the shrug thing (`¯\_(ツ)_/¯`) directly to Telegram results in this error:

    `Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 23`

and nothing appearing in Telegram.

I will keep trying to use simple-markdown, as it parses the markdown well, but generates bad (according to Telegram) HTML. I might just have to make a custom syntax tree converter to generate good HTML (using HTML because it is easier to get correct than markdown)

**Comment by alphachung** [comment]
Looks like the bold isn't parsed very well in simple-markdown. The way that both Discord's and Telegram's markdown have deviated from Gruber's original spec in different ways makes this tricky.

As you've said, and I agree, a custom syntax tree parser is the only way to get to near-perfect conversion between the two.

**Comment by Suppen** [comment]
Telegram just got an update making things even more complicated:
`— Send **bold** and __italic__ text in your messages.`
That is, raw messages not going through the @bold bot or other bots support some basic markdown different from the markdown these bots support (*bold* _italic_)

**Comment by Suppen** [comment]
This should now be fixed in commit 3e71d3faa8b470e2afc8737ba3bf935a35df08b6. Thanks to @alphachung for finding simple-markdown, the markdown parser used by Discord
