### ISSUE TITLE
Add ":" to the end of usernames on Telegram

### ISSUE THREAD

**Issue by alphachung** [Suppen/TediCross#20]
Currently, the messages from Discord to Telegram is styled as such:
> **Username**
> Message

But when the username becomes longer, on iOS, the Telegram notification banner becomes a bit confusing to read on first sight. Let me illustrate. 

---

This is the current normal notification, everything looks fine: 
![currentnormal](https://cloud.githubusercontent.com/assets/5276387/26752723/4d47cd60-4889-11e7-9fda-6b3c776de3c0.png)

But when the username of the Discord user becomes longer, the username wraps to the next line, so it kind of looks like the message itself: 
![currentlong](https://cloud.githubusercontent.com/assets/5276387/26752737/905bc7d2-4889-11e7-852e-85c54abad64c.png)

If the username is long and contains CJK characters, the problem becomes worse due to the way CJK characters are wrapped: 
![currentlongcjk](https://cloud.githubusercontent.com/assets/5276387/26752757/cacbd34e-4889-11e7-9ba9-aa9cbfe229bf.png)

When glancing these notifications quickly, it becomes a problem as the usernames look like the chat content. 

---

Therefore, I propose adding a ":" to the end of the usernames of Discord ➡️Telegram messages, or make it an option, so that the people getting notifications on iOS knows that it's just the username. 

![pnormal](https://cloud.githubusercontent.com/assets/5276387/26752787/6a2f3354-488a-11e7-9e96-8c21bf92b258.png)
![plong](https://cloud.githubusercontent.com/assets/5276387/26752788/6b82d760-488a-11e7-8042-f77554b0f277.png)
![plongcjk](https://cloud.githubusercontent.com/assets/5276387/26752789/6bccf746-488a-11e7-9c44-9fa832783024.png)

As these mockups show, adding the ":" to the end of usernames can allow users to easier distinguish between long usernames and the actual messages' content.

**Comment by Suppen** [comment]
Added an option for this in commit b1eb221441e148b9f744fe272adcaaead4a4a402
