### ISSUE TITLE
Replying from Telegram to a Discord User

### ISSUE THREAD

**Issue by DragonFlayer** [Suppen/TediCross#26]
A feature suggestion:

Add the Discord username when someone replies to the Telegram Bot 

Example 

>Discord user posts

>Telegram bot shares the post in telegram with the format 

DiscordUsername 
Message

>A Telegram user replies to that bot message 

>Discord bot shares the post in Discord with the format 

TelegramUsername (in reply to telegrambot) 
Message 

My suggestion is to make it so Telegram bot shares the full username of Discord users (Username#####) 

And that when someone in telegram replies to the bot, the bot sees which Discord user was replied to by reading the Discord username from the replied message, to which the Discord bot replies as

TelegramUsername (in reply to @DiscordUsername#####) 
Message

This could be a way to emulate Telegram replies in Discord, which lacks the feature

**Comment by Suppen** [comment]
This is now implemented in commit f51fccafe2702383230e92916269eccc5a423706
