### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by brik** [Suppen/TediCross#27]
Is there anything I need to do after the last update to get it running?

I am getting 

`npm ERR! Linux 3.10.0-327.3.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! tedicross@0.1.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tedicross@0.1.0 start script 'node main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tedicross package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tedicross
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tedicross
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kamilla/relay-bot-kittenz/npm-debug.log
`

when running npm start. Node is up to date

**Comment by Suppen** [comment]
Node is the correct version. Npm is a bit old, but that really shouldn't matter.

Could you try to delete the `node_modules/` directory and run `npm install` again?

**Comment by negingai** [comment]
I also failed at starting up.
I am using nodejs v8.5.0 on CentOS7 and the npm version is 5.3.0.

after npm install 
npm WARN tedicross@0.1.0 No repository field.
npm WARN tedicross@0.1.0 No license field.

after npm start I got these messages
> node main.js

fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'settings.json'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at Object.<anonymous> (/home/negi/TediCross/lib/settings.js:13:32)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tedicross@0.1.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tedicross@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-13T08_39_48_848Z-debug.log

**Comment by Suppen** [comment]
@negingai it appears you don't have a settings.json file. Did you follow the step-by-step installation guide? It tells you how to make it

**Comment by negingai** [comment]
@Suppen I found that I typed a wrong file name of settings.json, now it runs well.

**Comment by brik** [comment]
Deleting node_modules fixed it, thanks!
