### ISSUE TITLE
Multi-Group/Multi-Channel Support

### ISSUE THREAD

**Issue by DragonFlayer** [Suppen/TediCross#29]
Since Telegram doesn't have support for multiple 'channels' in a 'server' as Discord does, some group owners split their group chats into several to try and simulate such organization you get from discord by having several channels in a single server

For Example:

A Telegram Community may have: Main Group, Admin Group, Media Group, etc
The same Community has a Discord with the Channels: Main, Admin, Media, etc

This feature request proposes that, using the same two bots, add support for mapping multiple telegram groups to multiple discord channels in the same server

Rather than having to run a new tedicross mapped to two new bots, we could have a single instance of tedicross using only the two bridge bots being aware of which group and channel are related and mapping them accordingly for bridging

**Comment by Suppen** [comment]
The architecture of TediCross doesn't really allow this. It will require a lot of rewriting.

I will take a look at what can be done, but I promise nothing

**Comment by Suppen** [comment]
Thanks to the awesome work of @molteber this is now possible!
