### ISSUE TITLE
Starting with + from discord, shows as undefined on telegram.

### ISSUE THREAD

**Issue by Skyrid3r** [Suppen/TediCross#31]
Bot doesn't appear to see the + symbol as normal text, so it shows as undefined in telegram. Example shown below as an image:

![photo_2017-10-10_15-53-39](https://user-images.githubusercontent.com/6794064/31390089-41759bc0-add3-11e7-9ea8-fa1b082136f4.jpg)
![photo_2017-10-10_15-53-44](https://user-images.githubusercontent.com/6794064/31390093-4347b028-add3-11e7-8d63-5b3f039abb57.jpg)

**Comment by Suppen** [comment]
This is an issue with the markdown parser. It interprets "+ something" as an unordered list with one element: "something". You get the same result if you use what Markdown counts as an ordered list: "1. something"

I will find a fix

**Comment by Suppen** [comment]
Should now be fixed in commit bb16d6ff7fe5084467a8b17df9188d80bee5c8e5
