### ISSUE TITLE
Make TediCross able to forward messages from Discord to a Telegram channel instead of a group

### ISSUE THREAD

**Issue by Suppen** [Suppen/TediCross#34]
TediCross currently enforces integral Telegram chat IDs. Channels have names, and the bot can therefore not send messages to channels.

This should be an easy fix

**Comment by Suppen** [comment]
I'm having no success adding a bot to my test channel. Is this possible?

**Comment by Suppen** [comment]
Got it into my test channel

**Comment by Suppen** [comment]
Strange thing... Channels are supposed to have chat ID `@channelName`, but that won't work with my test. Putting the bot in the channel, sending a message, and manually getting updates for the bot reveals that it has an integral chat ID, just like groups. Using this ID works

Aquiring this ID is done as follows:
* Stop TediCross (or use another bot)
* Go to the channel in question and add the bot as an administrator
  * Click on the channel's name, and then "Administrators" under "Members", and then "Add administrator" at the bottom
  * Enter the bot's username and click it. Give it whatever rights you want
* Go to the URL https://api.telegram.org/botTOKEN/getUpdates (with your actual bot token substituted for "TOKEN")
* In the response you see a chat ID under `result[0].channel_post.chat.id`. Put this ID into settings.json`

**Comment by Suppen** [comment]
This does mean it has apparently always worked, so no code update is necessary

**Comment by amirnilchi2017** [comment]
but I get `{"ok":false,"error_code":404,"description":"Not Found"}` when I went to URL https://api.telegram.org/botTOKEN/getUpdates with my bot token

**Comment by Suppen** [comment]
The issue @amirnilchi2017 had was resolved in chat. He substituted the whole `botTOKEN` instead of just `TOKEN` with the token

**Comment by Suppen** [comment]
For future readers, the approach for getting the char ID of a channel has been massively simplified. It now works the same way as getting the chat ID for any other chat
