### ISSUE TITLE
Messages from other bots don't get forwarded

### ISSUE THREAD

**Issue by Fabian42** [Suppen/TediCross#43]
I have a Telegram group with me, the Discord bot and a reminder bot. No messages from the reminder bot get forwarded to Discord.

This might be intentional to avoid an infinite loop of two Discord/Telegram bots in the same Discord chat and the same Telegram chat forwarding each other's messages back and forth, but if I set it up that way, it's really my fault. So allowing this would be only beneficial in almost all cases.

Other people's message do get forwarded.

**Comment by trgwii** [comment]
Telegram prevents any bot from reading another bots' messages. In Telegram a bot **CAN'T** see another bot, thus not know of any messages sent from it either.

**Comment by trgwii** [comment]
Here's a paragraph from [Telegram](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots):

**Why doesn't my bot see messages from other bots?**
Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.
