### ISSUE TITLE
Add option to remove emoji from stickers

### ISSUE THREAD

**Issue by CvoidWyvern** [Suppen/TediCross#48]
Stickers relayed to discord currently also post the emoji that the sticker uses.  This takes up an extra line that really isn't needed, and adds up quickly when using many stickers.  Also with the emoji removed and #39 in use, multi-sticker stickers would work close to properly instead of having ~3 lines of space between them.

**Comment by Suppen** [comment]
Fixed in commit 5ee27a4d730c5418affcf794749ccb89bbbedf50
