### ISSUE TITLE
Feature suggestion: "skipOldMessages" option for Discord

### ISSUE THREAD

**Issue by Fabian42** [Suppen/TediCross#50]
Simple reason: If my bot doesn't run for a while, I want it to send all messages to Telegram that were written in Discord in the meantime.

**Comment by Suppen** [comment]
Almost done. Please be aware of this:

https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

It will cause problems which I can't do anything about

**Comment by Suppen** [comment]
I'm also having problems synchronizing them, so they will arrive at Telegram out of order. See also https://github.com/Suppen/TediCross/issues/45

**Comment by Suppen** [comment]
Implemented in commit ff425f810fa6add5f35a86bda4028a8899dc0f7a, but not sure how useful it is, especially since the messages will probably arrive totally out of order

**Comment by Fabian42** [comment]
Maybe the bot could read the send time of the message and sort by that itself? Then only messages that arrived in the same second would be unsorted.

**Comment by Suppen** [comment]
I already do that. They still arrive out of order on Telegram, because I send them without bothering waiting to see if it was received by Telegram. I might fix this in the big April rewrite
