### ISSUE TITLE
Doesn't seem to relay posts by Telegram bots

### ISSUE THREAD

**Issue by rdaltri** [Suppen/TediCross#52]
Hey everyone,

Have noticed that posts by Telegram bots to the Telegram channel do not get relayed to the Discord server.  Noticed this behavior with several different bots.  Is this something that is limited by Telegram/Discord itself?  Any input would be greatly appreciated :)

Thanks in advance.

**Comment by Fabian42** [comment]
Telegram doesn't allow bots to see the messages of other bots, to avoid infinite loops. See #43.

**Comment by rdaltri** [comment]
Thanks for the quick reply Fabian42.  I will close this issue now.

**Comment by Suppen** [comment]
See also the [FAQ in the README](https://github.com/Suppen/TediCross#the-telegram-bot-doesnt-relay-messages-sent-by-other-bots)
