### ISSUE TITLE
Hability to tell new members on both platforms

### ISSUE THREAD

**Issue by SkateWarp** [Suppen/TediCross#60]
It's possible to send an alert message when a new member joined to the Telegram group or Discord server?
Like 

_SkateWarp joined to [Telegram group name]_ to the Discord server.

for Discord to Telegram, at first I thought it woudn't be possible to send an alert message from one text channel, but what if you use the bot with the server roles to separate the users from others channels?

**Comment by Suppen** [comment]
This has now been implemented in commit 2296b09dadf0ea508a561ac74e9ec860f0dd172c

It also has two per-bridge settings associated with it: `bridge.telegram.relayJoinLeaveMessages` and `bridge.discord.relayJoinLeaveMessages`, which toggles this functionality
